### ISSUE TITLE
docker-compose up on build-service and oba fails

### ISSUE THREAD

**Issue by cohenoshri** [OneBusAway/docker#14]
see error produced by docker-compose:

> ERROR: Service 'oba' failed to build: COPY failed: stat /var/lib/docker/overlay2/b16bedda9d8f530d93774142e7422c261d0b33735d45a865072005c910576a9f/merged/app/onebusaway-transit-data-federation-builder/target/onebusaway-transit-data-federation-builder-2.0.0-SNAPSHOT-withAllDependencies.jar: no such file or directory

**Comment by brodyFlannigan** [comment]
Similar issue here
@barbeau could you maybe look into this?
![image](https://user-images.githubusercontent.com/46612183/80493382-52942780-8933-11ea-8bd6-2edea382ad7d.png)

**Comment by barbeau** [comment]
It looks like we're on version `2.0.1-SNAPSHOT` now in the oba-app-modules project (https://github.com/OneBusAway/onebusaway-application-modules/blob/master/pom.xml#L10), so if you change the copy command to that instead of `2.0.0-SNAPSHOT`, hopefully it should find the file 🤞. If that works, could you open a PR?

When 2.0.1 is released, we should really switch to checking that tag out instead of the master branch.

**Comment by brodyFlannigan** [comment]
👍 it worked!!!

I will open a PR shortly.

**Comment by barbeau** [comment]
Fixed via https://github.com/OneBusAway/onebusaway-docker/pull/18
